### ISSUE TITLE
not save the change DB

### ISSUE THREAD

**Issue by PBlips** [pbaity/rocketchat-dark-mode#156]
Hi, 
I have a problem. I am working with docker and when importing the database to a new container it does not save the dark mode configuration and I have to configure it again manually. Would someone know how to explain why that change is not saved?

Thanks !.

**Comment by pbaity** [comment]
Hi @PBlips , welcome! Congrats on your first issue. I haven't used the Docker setup before so I've got some reading to do to be able to help. Do you mean that when you import the database to a new container, the dark mode custom code is not retained and needs to be copied in again? Or just that your current mode (dark or light) is not retained? Feel free to share some screenshots too.

**Comment by PBlips** [comment]
Well, when importing the database I have to put the codes again.
I hope it can be fixed in case you need to make a backup and thus avoid looking for the corresponding codes again.
Thank you.

**Comment by pbaity** [comment]
@PBlips Sorry for the long delay getting back to this issue. After some investigation I've determined this must be a Rocket.Chat issue and not something caused by the dark mode code. I didn't immediately find this reported among their issues, but you can open a new one in their repo [here](https://github.com/RocketChat/Rocket.Chat/issues). Thanks.
