### ISSUE TITLE
Scrollbar thumb almost invisible in Rocket Chat

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#74]
**Describe the bug**
scrollbar-thumb almost invisible.
It's not a dark mode issue, it's Rocket Chat itself issue
I want to fix that in dark mode CSS

**To Reproduce**
1. Go to sidebar
2. Try to scroll up and down
3. Scrollbar thumb almost invisible

**Expected behavior**
Visible scrollbar thumb

**Screenshots**
![image](https://user-images.githubusercontent.com/4023037/95699846-34ef1c00-0c4e-11eb-848d-ffef13c28c80.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 85

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9 SE
 - OS: Android 10
 - Browser Chrome
 - Version 85

**Additional context**
I have a fix for that

**Comment by pbaity** [comment]
Not fixing this issue because the scroll bar is visible in dark mode. As the issue states, this is a Rocket.Chat bug. We won't include fixes for Rocket.Chat light mode bugs in this repository in order to keep in clean.

That said, if anyone wants to copy and paste @ankar84 's fix into your local Rocket.Chat instance's CSS styles, this seems to fix it for the time being:
```css
*::-webkit-scrollbar-thumb {
	background-color: rgba(255, 255, 255, 0.15);
}
```
Thanks for raising this issue.
