### ISSUE TITLE
Room info not contrast

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#8]
**Room info** not contrast
![image](https://user-images.githubusercontent.com/4023037/74213171-1abd0280-4ca9-11ea-90b9-6334d609394f.png)
**Notifications Preferences** too
![image](https://user-images.githubusercontent.com/4023037/74216755-6fb34580-4cb6-11ea-8594-b114849722c2.png)

**Comment by pbaity** [comment]
@ankar84 Thanks for pointing this out. I'll work on this when I can unless you or someone else picks it up, but just to make sure I don't miss anything, please describe what exactly you see that needs to be fixed in the Room Info and Notification Preferences. See the bug report issue template for the types of details we're looking for.

**Comment by ankar84** [comment]
> @ankar84 Thanks for pointing this out. I'll work on this when I can unless you or someone else picks it up, but just to make sure I don't miss anything, please describe what exactly you see that needs to be fixed in the Room Info and Notification Preferences. See the bug report issue template for the types of details we're looking for.
> 
> Edit: I was on slow internet there for a minute, so your screenshots didn't load. Those are very helpful, thank you. Still feel free to describe any specifics and when I get a PR ready, I'll tag you in it to make sure I fixed everything you see here.

Hi!
I understand.
I'm not a developer or CSS master, so now I can only get div classes with contrast problems:
rc-switch-double
rc-switch-double__label disabled
rc-switch-double__description
rc-switch-double__label
rc-switch-double__description
